version: '3'
services:
  app:
    image: app
    links:
      - database
    depends_on:
      - database
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./:/app"
    environment:
      TELEGRAM_TOKEN: "665864512:AAHJ7mnoPo7KhrJx7XKwUoEFRgmjQXRWkYo"

  database:
    image: postgres
    container_name: postgres-container
    restart: always
    expose:
      - "5432"
    ports:
      - "5444:5432"
    volumes:
      - hero-volume:/var/lib/postgresql/data

    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "example"

  rabbitmq:
    image: rabbitmq

  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A tasks beat --loglevel=info
    depends_on:
      - database
      - rabbitmq
    environment:
      - C_FORCE_ROOT=true
      - DEBUG_MODE=false
    volumes:
      - "./:/app"

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A tasks worker --loglevel=info
    depends_on:
      - database
      - rabbitmq
      - celery_beat
    environment:
      - C_FORCE_ROOT=true
      - DEBUG_MODE=false
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672
      - TELEGRAM_TOKEN=665864512:AAHJ7mnoPo7KhrJx7XKwUoEFRgmjQXRWkYo
    volumes:
      - "./:/app"


  flower:
    image: mher/flower
    environment:
      - CELERY_BROKER_URL=amqp://rabbitmq
    ports:
      - 5555:5555

volumes:
  hero-volume:
    driver: local