# docker-compose.yml
version: '3'
services:
  telegram-app:
    image: telegram-app
    links:
      - database
    depends_on:
      - database
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./:/app"

  database:
    image: postgres
    container_name: postgres-container
    restart: always
    expose:
      - "5432"
    ports:
      - "5444:5432"
    volumes:
      - hero-volume:/var/lib/postgresql/data

    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "example"

volumes:
  hero-volume:
    driver: local